[tool.briefcase]
project_name = "Bitcart Vault"
bundle = "com.bitcart"
version = "1.0.0"
url = "https://github.com/bitcart/bitcart-vault"
license = "MIT license"
author = 'Bitcart'
author_email = "hello@bitcart.ai"

[tool.briefcase.app.vault]
formal_name = "Bitcart Vault"
description = "a bridge to HWI to access hardware devices functions"
icon = "src/vault/resources/vault"
sources = ['src/vault']
requires = [
    'pyside2==5.15.2.1',
    'flask==2.2.2',
    'flask-cors==3.0.10',
    'hwi==2.2.0'
]


[tool.briefcase.app.vault.macOS]
requires = [
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.vault.linux]
requires = []

[tool.briefcase.app.vault.linux.appimage]
system_requires = []
linuxdeploy_plugins = []

[tool.briefcase.app.vault.linux.flatpak]
flatpak_runtime = 'org.kde.Platform'
flatpak_runtime_version = '6.3'
flatpak_sdk = 'org.kde.Sdk'

[tool.briefcase.app.vault.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.vault.iOS]
supported = false

[tool.briefcase.app.vault.android]
supported = false

[tool.briefcase.app.vault.web]
supported = false
