name: Build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019", "ubuntu-18.04", "macos-10.15"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip install -U wheel setuptools pip
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller vault.spec
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'windows-2019' }}
        with:
          name: bitcart-vault-windows.exe
          path: dist/vault.exe

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        with:
          name: bitcart-vault-linux
          path: dist/vault

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'macos-10.15' }}
        with:
          name: bitcart-vault-macos
          path: dist/vault
