name: Build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        os-name: ["macOS", "windows", "linux"]
        include:
          - os-name: macOS
            platform: macos-12
            briefcase-data-dir: ~/Library/Caches/org.beeware.briefcase
            pip-cache-dir: ~/Library/Caches/pip
            docker-cache-dir: ~/Library/Containers/com.docker.docker/Data/vms/0/
            output-path: macOS/Bitcart Vault-1.0.0.dmg
          - os-name: windows
            platform: windows-latest
            briefcase-data-dir: ~\AppData\Local\BeeWare\briefcase\Cache
            pip-cache-dir: ~\AppData\Local\pip\Cache
            docker-cache-dir: C:\ProgramData\DockerDesktop
            output-path: windows/Bitcart Vault-1.0.0.msi
          - os-name: linux
            # Need to use at least 22.04 to get the bugfix in flatpak for handling spaces in filenames.
            platform: ubuntu-22.04
            briefcase-data-dir: ~/.cache/briefcase
            pip-cache-dir: ~/.cache/pip
            # cache action cannot cache docker images (actions/cache#31)
            # docker-cache-dir: /var/lib/docker
            output-path: linux/Bitcart_Vault-1.0.0-x86_64.AppImage
    steps:
      - name: Cache Briefcase tools
        uses: actions/cache@v3
        with:
          key: briefcase-${{ matrix.platform }}
          path: |
            ~/.cookiecutters
            ${{ matrix.briefcase-data-dir }}
            ${{ matrix.pip-cache-dir }}
            ${{ matrix.docker-cache-dir }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install briefcase
        run: |
          pip install briefcase
      - name: Build App
        run: |
          briefcase create
          briefcase build
          briefcase package --adhoc-sign
      - name: Upload App artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bitcart-vault-${{ matrix.os-name }}
          path: ${{ matrix.output-path }}

      - name: Add to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{ matrix.output-path }}"
